pipeline:
  name: Build go-pipeline-sample
  identifier: Build_hemant0041_go_pipeline_sample_1735881824397
  projectIdentifier: test2
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: run unit test
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      set +e 
                      go get gotest.tools/gotestsum
                      gotestsum --format=standard -verbose --junitfile unit -tests.xml
                      exit 0
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: hemant0041/go-pipeline-sample
        build: <+input>
