pipeline:
  name: Build go-pipeline-sample
  identifier: Build_hemant0041_go_pipeline_sample_1735815118645
  template:
    templateRef: Hemant_Kumar_Mahato
    versionLabel: v1
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
      stages:
        - stage:
            identifier: build
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: dockerbuild
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: <+input>
  projectIdentifier: default_project
  orgIdentifier: default
