pipeline:
  name: Build go-pipeline-sample
  identifier: Build_hemant0041_go_pipeline_sample_1735878850179
  projectIdentifier: test2
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        template:
          templateRef: testing
          versionLabel: v1
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: hemant0041/go-pipeline-sample
        build: <+input>
